# Generated by Django 4.2.7 on 2023-12-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='countries',
            field=models.CharField(choices=[('russia', 'ru'), ('thailand', 'thai'), ('norway', 'nor'), ('southafrica', 'south')], default='', max_length=20),
        ),
    ]
