# Generated by Django 4.2.7 on 2023-12-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tour_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='countries',
            field=models.CharField(choices=[('norway', 'nor'), ('thailand', 'thai'), ('russia', 'ru'), ('southafrica', 'south')], default='', max_length=20),
        ),
    ]
